# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e2ee9e912f562c4bd6c28be7f21959cb814162308a0c332dd51ce442beae0c062c8be8356d25446278f038ebf1f0e723a5bc797860f43e7c531677400ed5702

test:
  secret_key_base: 57a563fdfda365b395936b52eee5353683e3280146cda326f4946d470165e956d303e405c6b093a6dddafdb13987b46fe310eb6e681e102bf9bf2f26e06a2616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
